"""固定 demo：reflect_on_failure → optimize_skill 端到端。

模拟 ``broken_skill`` 跑挂之后系统自检 → 自动产出 ``broken_skill_evolved/``。
所有产物落到 ``data/outputs/demo_skill_evolution/``，作为"反思 + 自我进化"的存档证据。

为什么不走 planner：
- planner 触发 reflection 链路依赖 LLM 自由决策，不可重现
- reflection / optimize_skill 真实代码（AST 校验、文件落盘、SkillPatch 产物）都被走过
- 只有 LLM 回复用 canned 替换

执行：``python scripts/demo_skill_evolution.py``
"""

from __future__ import annotations

import asyncio
import json
import shutil
import sys
import textwrap
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT))

from src.dynamic_os.contracts.skill_io import SkillContext  # noqa: E402
from src.dynamic_os.skills.builtins.reflect_on_failure.run import run as reflect_run  # noqa: E402
from src.dynamic_os.skills.builtins.optimize_skill.run import run as optimize_run  # noqa: E402

DEMO_SKILL_ROOT = REPO_ROOT / "scripts" / "demo_assets"
BROKEN_SKILL_ID = "broken_skill"
OUTPUT_DIR = REPO_ROOT / "data" / "outputs" / "demo_skill_evolution"

REFLECTION_RESPONSE = {
    "root_cause": (
        "broken_skill iterates ``source.get('authors')`` directly. When "
        "paper_search_mcp returns authors as a ';'-separated string (the actual "
        "real-world shape), the for-loop iterates *characters* not authors, so "
        "the length check raises immediately on the first character."
    ),
    "failure_category": "input_handling",
    "suggested_fix": (
        "Normalize the authors field to list[str] before iterating: detect string "
        "input and split on ';' (BibTeX-style ' and ' fallback). Single author = "
        "single-element list. Same heuristic as runtime._normalize_authors."
    ),
    "should_evolve": True,
    "confidence": 0.92,
}

EVOLVED_RUN_PY = '''"""Evolved version of broken_skill — adds authors normalization at the boundary.

Generated by optimize_skill (demo). The fix mirrors runtime._normalize_authors:
detect string-form authors from paper_search_mcp and split on ';' before iterating.
"""

from __future__ import annotations

from src.dynamic_os.artifact_refs import make_artifact, source_input_refs
from src.dynamic_os.contracts.route_plan import RoleId
from src.dynamic_os.contracts.skill_io import SkillContext, SkillOutput


def _normalize_authors(value) -> list[str]:
    if value is None:
        return []
    if isinstance(value, (list, tuple)):
        items = [str(a).strip() for a in value if str(a).strip()]
        # 字符列表（fetcher 误把字符串 list() 化）→ 重新拼回再走字符串解析
        if len(items) >= 4 and all(len(a) <= 1 for a in items):
            return _normalize_authors("".join(items))
        return items
    if isinstance(value, str):
        text = value.strip()
        if not text:
            return []
        if " and " in text:
            return [p.strip() for p in text.split(" and ") if p.strip()]
        if ";" in text:
            return [p.strip() for p in text.split(";") if p.strip()]
        return [text]
    text = str(value).strip()
    return [text] if text else []


async def run(ctx: SkillContext) -> SkillOutput:
    sources: list[dict] = []
    for art in ctx.input_artifacts:
        if art.artifact_type == "SourceSet":
            sources.extend(art.payload.get("sources", []))

    keywords: list[str] = []
    for source in sources:
        for author in _normalize_authors(source.get("authors")):
            if len(author) >= 2:
                keywords.append(author)

    artifact = make_artifact(
        node_id=ctx.node_id,
        artifact_type="KeywordSet",
        producer_role=RoleId(ctx.role_id),
        producer_skill=ctx.skill_id,
        payload={"keywords": keywords, "evolved": True},
        source_inputs=source_input_refs(ctx.input_artifacts),
    )
    return SkillOutput(success=True, output_artifacts=[artifact])
'''


class _FakeGateway:
    """reflect_on_failure / optimize_skill 实际只用 ctx.tools.llm_chat。"""

    def __init__(self) -> None:
        self._llm_calls = 0

    async def llm_chat(self, messages, **kwargs):  # noqa: ANN001
        sys_msg = (messages[0].get("content") if messages else "") or ""
        if "skill failure analyst" in sys_msg.lower():
            return json.dumps(REFLECTION_RESPONSE)
        if "skill code optimizer" in sys_msg.lower():
            return f"```python\n{EVOLVED_RUN_PY}\n```"
        # 没匹配上的 prompt 直接 raise——上游 skill 改 system prompt 时立刻指出来。
        raise RuntimeError(
            f"_FakeGateway.llm_chat: unmocked system prompt: {sys_msg[:200]!r}"
        )


def _make_ctx(*, skill_id: str, role_id: str, run_id: str, node_id: str,
              goal: str, input_artifacts, gateway, config) -> SkillContext:
    return SkillContext(
        skill_id=skill_id,
        role_id=role_id,
        run_id=run_id,
        node_id=node_id,
        goal=goal,
        input_artifacts=list(input_artifacts),
        tools=gateway,
        user_request="Demonstrate the reflect_on_failure → optimize_skill self-improvement chain.",
        config=config,
        timeout_sec=60,
    )


def _dump_artifact(artifact, dest: Path) -> None:
    dest.write_text(
        json.dumps(artifact.model_dump(mode="json"), ensure_ascii=False, indent=2),
        encoding="utf-8",
    )


async def main() -> int:
    if OUTPUT_DIR.exists():
        shutil.rmtree(OUTPUT_DIR)
    OUTPUT_DIR.mkdir(parents=True)

    # optimize_skill 内部 mkdir(parents=True, exist_ok=True) 会建 evolved_skills/，无需提前建
    config = {
        # optimize_skill 用 skill_roots 找原始 run.py
        "skill_roots": [str(DEMO_SKILL_ROOT)],
        # workspace_root/evolved_skills 是落盘地址
        "workspace_root": str(OUTPUT_DIR),
    }
    gateway = _FakeGateway()
    run_id = "demo_skill_evolution"

    # --- reflect_on_failure ---
    reflect_ctx = _make_ctx(
        skill_id="reflect_on_failure", role_id="analyst",
        run_id=run_id, node_id="demo_reflect",
        goal=(
            "skill_id: broken_skill failed during execution. It raised "
            "ValueError('author name too short') on the first iteration because "
            "the input authors field came in as a ';'-separated string instead "
            "of a list. Analyze the failure and propose a fix."
        ),
        input_artifacts=[],
        gateway=gateway, config=config,
    )
    reflect_out = await reflect_run(reflect_ctx)
    if not reflect_out.success:
        print(f"reflect failed: {reflect_out.error}", file=sys.stderr)
        return 2
    reflection_artifact = reflect_out.output_artifacts[0]
    _dump_artifact(reflection_artifact, OUTPUT_DIR / "reflection_report.json")

    # --- optimize_skill ---
    optimize_ctx = _make_ctx(
        skill_id="optimize_skill", role_id="experimenter",
        run_id=run_id, node_id="demo_optimize",
        goal="Generate an evolved version of broken_skill that fixes the iteration bug.",
        input_artifacts=[reflection_artifact],
        gateway=gateway, config=config,
    )
    optimize_out = await optimize_run(optimize_ctx)
    if not optimize_out.success:
        print(f"optimize failed: {optimize_out.error}", file=sys.stderr)
        return 3
    patch_artifact = optimize_out.output_artifacts[0]
    _dump_artifact(patch_artifact, OUTPUT_DIR / "skill_patch.json")

    evolved_path = Path(patch_artifact.payload["evolved_path"])
    summary = {
        "reflection": {
            "root_cause": reflection_artifact.payload["root_cause"][:200] + "...",
            "category": reflection_artifact.payload["failure_category"],
            "should_evolve": reflection_artifact.payload["should_evolve"],
            "confidence": reflection_artifact.payload["confidence"],
        },
        "evolution": {
            "original_skill_id": patch_artifact.payload["original_skill_id"],
            "evolved_skill_id": patch_artifact.payload["evolved_skill_id"],
            "evolved_path": str(evolved_path.relative_to(REPO_ROOT)),
            "validation_passed": patch_artifact.payload["validation_passed"],
            "requires_registry_refresh": patch_artifact.payload["requires_registry_refresh"],
        },
    }
    (OUTPUT_DIR / "summary.json").write_text(
        json.dumps(summary, ensure_ascii=False, indent=2), encoding="utf-8"
    )

    readme = textwrap.dedent(f"""\
    # Demo: reflect_on_failure → optimize_skill

    端到端跑了一次 skill 自我进化：

    1. **reflect_on_failure** 收到 ``broken_skill`` 的失败上下文，输出 ReflectionReport：
       - root_cause: {reflection_artifact.payload['root_cause'][:140]}...
       - confidence: {reflection_artifact.payload['confidence']}
    2. **optimize_skill** 读 ``scripts/demo_assets/broken_skill/run.py`` 原始源码，
       基于 reflection 让 LLM 产出修复版，AST 校验通过后写到
       ``evolved_skills/broken_skill_evolved/``。

    产物清单：
    - ``reflection_report.json``      ReflectionReport 产物
    - ``skill_patch.json``            SkillPatch 产物（含 evolved_path / validation_passed）
    - ``evolved_skills/broken_skill_evolved/``
        * ``run.py``     LLM 产出的修复版源码
        * ``skill.yaml`` 自动派生的 spec（id 加 ``_evolved`` 后缀）
        * ``skill.md``   占位说明

    重新生成：``python scripts/demo_skill_evolution.py``
    """)
    (OUTPUT_DIR / "README.md").write_text(readme, encoding="utf-8")
    print("\nDemo OK. Artifacts written to:", OUTPUT_DIR)
    print("  evolved skill at:", evolved_path)
    return 0


if __name__ == "__main__":
    raise SystemExit(asyncio.run(main()))
